#!/usr/bin/env python3
"""Generates the weather widgets' picker previews (res/layout/wx_preview_*.xml).

Android 12+ draws a widget's picker preview from a static layout (`android:previewLayout`). These
are built from the real frame and entry layouts with sample data filled in, so the previews can't
drift from what the widgets render. Re-run after changing any wx_* layout:

    python3 android/scripts/gen_weather_widget_previews.py
"""

import copy
import os
import xml.etree.ElementTree as ET

A = "http://schemas.android.com/apk/res/android"
ET.register_namespace("android", A)
LAYOUT = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "res", "layout")

# Sample sites (values as seen live on 2026-09-28).
SITES = [
    dict(label="MONET/S", icon="wx_ic_clear_night", temp="5.4°", humid="66 %", wind="36 km/h", sky="-31.5°",
         line="Clear · 2 min ago", wind_warn=True),
    dict(label="IAG 50cm", icon="wx_ic_sky_unknown", temp="18.9°", humid="66 %", wind="5 km/h", sky="n/a",
         line="No sky sensor · 2 min ago", wind_warn=False),
]


def a(name):
    return f"{{{A}}}{name}"


def load(name):
    return ET.parse(os.path.join(LAYOUT, name + ".xml")).getroot()


def by_id(root, view_id):
    for el in root.iter():
        if el.get(a("id")) == f"@+id/{view_id}":
            return el
    raise KeyError(view_id)


def set_attrs(root, view_id, **attrs):
    el = by_id(root, view_id)
    for key, value in attrs.items():
        el.set(a(key), value)


def pill(root):
    set_attrs(root, "wx_pill", text="OK", textColor="@color/wx_ok", background="@drawable/wx_pill_ok")


def list_row(site):
    row = load("wx_list_row")
    set_attrs(row, "wx_icon", src=f"@drawable/{site['icon']}")
    set_attrs(row, "wx_label", text=site["label"])
    set_attrs(row, "wx_line", text=f"{site['humid']} · {site['wind']}")
    set_attrs(row, "wx_temp", text=site["temp"])
    pill(row)
    return row


def tile(site):
    t = load("wx_tile")
    set_attrs(t, "wx_icon", src=f"@drawable/{site['icon']}")
    set_attrs(t, "wx_label", text=site["label"])
    set_attrs(t, "wx_temp", text=site["temp"])
    set_attrs(t, "wx_line", text=f"{site['humid']} · {site['wind']}")
    pill(t)
    return t


def block(site):
    b = load("wx_detail_block")
    set_attrs(b, "wx_icon", src=f"@drawable/{site['icon']}")
    set_attrs(b, "wx_label", text=site["label"])
    set_attrs(b, "wx_line", text=site["line"])
    set_attrs(b, "wx_temp", text=site["temp"])
    pill(b)
    for i, (label, value) in enumerate([("Humidity", site["humid"]), ("Wind", site["wind"]), ("Sky", site["sky"])], 1):
        set_attrs(b, f"wx_chip{i}_label", text=label)
        set_attrs(b, f"wx_chip{i}_value", text=value)
    if site["wind_warn"]:
        set_attrs(b, "wx_chip2", background="@drawable/wx_chip_warn")
        set_attrs(b, "wx_chip2_value", textColor="@color/wx_warn")
    return b


def frame(children):
    root = load("wx_frame")
    set_attrs(root, "wx_info", text="2 min ago")
    content = by_id(root, "wx_content")
    for child in children:
        content.append(child)
    return root


def write(name, root):
    ET.indent(root, space="    ")
    body = ET.tostring(root, encoding="unicode")
    header = ('<?xml version="1.0" encoding="utf-8"?>\n'
              "<!-- Generated by android/scripts/gen_weather_widget_previews.py. Do not edit. -->\n")
    with open(os.path.join(LAYOUT, name + ".xml"), "w", encoding="utf-8") as f:
        f.write(header + body + "\n")


def main():
    write("wx_preview_list", frame([list_row(s) for s in SITES]))

    row = load("wx_tile_row")
    for s in SITES:
        row.append(tile(s))
    write("wx_preview_tiles", frame([row]))

    write("wx_preview_detailed", frame([block(s) for s in SITES]))


if __name__ == "__main__":
    main()
